### ISSUE TITLE
Visualize the session using an /test/session view to see attributes stored

### ISSUE THREAD

**Issue by nowucca** [nowucca/SimpleAffableBean#27]
Add a visualization of session attributes to a new test/session.jsp page to demonstrate the contents of the session and how they change over time.  This could simply be a simple table, based on iterating over the HttpSession attributes.

**Comment by nowucca** [comment]
If we implement #8, this should visualize the internals of the SimpleAffableBeanSession object as well as the HttpSession.

**Comment by tippyweb** [comment]
@nowucca 

I'm back!  I'd like to work on this issue.  Please let me know how this page is supposed to be accessed.  A button in the Admin home page?  Thank you!!

**Comment by tippyweb** [comment]
Hello @nowucca

I created a new menu link for "view session" in the Admin Menu and looked into the session attributes with the debug mode.  There were more than a dozen attributes and about a half of them had nested attributes.  How do you want to get it displayed in this page?  Only the top level attributes only or all nested ones too?  Thank you so much!!

**Comment by nowucca** [comment]
Welcome back!

It would help if I could answer on a case by case basis.
For the objects like the cart definitely showing contents in a nice human readable format is the goal.  On the whole that's true for others that WE are in charge of too.

For the language ones it would nice to display language and locale.

Other than that let's use your discretion!

**Comment by nowucca** [comment]
I'm imagining a table with name/human readable value for the display.  Menu link is a good choice!

**Comment by tippyweb** [comment]
Hello @nowucca 

Thank you so much for your feedback!  This is very helpful!!
Something else just came up.
But would like to resume working on it from Wed/Thu next week.
I will keep you posted.
After this issue, I'd like to come back to #29 Phase 2.

Have a great weekend, @nowucca !!

**Comment by nowucca** [comment]
I'm in Australia until Thursday @tippyweb so no problem with the timing.

Talk to you later!

**Comment by tippyweb** [comment]
Hello @nowucca 

Welcome back from Australia!!
I resumed working on this issue earlier today and it's almost done.
I should be able to contact you on Friday.  Thank you!!

**Comment by tippyweb** [comment]
Hello @nowucca 

I just made a pull request for Issue #27.
I was having issue in displaying the selected language.
Any assistance is appreciated.
Right now, it simply displays the browser locale, which needs to be updated.

Please let me know if you think of any additional data to be included on this page.
Thank you so much, @nowucca, and have a great weekend!!

**Comment by nowucca** [comment]
Hi @tippyweb!  Thanks so much for working on this.
I will look at this today or tonight and fix and merge it if I can.

**Comment by tippyweb** [comment]
Hello @nowucca 

Thank you so much for your message!  Your help with the website local data would be awesome!!  If there are more to add, please let me know.  I will come back to this next week -- sorry, something else came up again!  Thanks much for your patience, @nowucca. Have a great week!!

**Comment by nowucca** [comment]
Hi @tippyweb, I will try to get back to this on Tuesday.  Lots of stuff to get ready for work.

**Comment by nowucca** [comment]
Ok @tippyweb, I've made some changes and merged to master.  Thanks for your help!

If you could cast an eye over them, the key changes are:
* started using a view model approach for the admin session page
* added in the all of the session's session attributes to the page

Please see:
https://github.com/nowucca/SimpleAffableBean/pull/34/commits/23cc4712f9adbee46bbd082e871e411e8fa21d2a

**Comment by tippyweb** [comment]
Good morning, @nowucca 

Wow, that's sooo nice!!  Thank you so much for fixing and updating this page -- Simply awesome!!!!
