### ISSUE TITLE
Make the documentation site links local to this site

### ISSUE THREAD

**Issue by nowucca** [nowucca/SimpleAffableBean#9]
This means (no https://phlow.github.io/feeling-responsive/ links) and clean up all external references in the bare bones version.

**Comment by morrme** [comment]
would this be for README or all of the files in the `/docs` directory?

**Comment by nowucca** [comment]
Hey @morrme I just added help-wanted as an experiment, thanks for showing up.
I closed this issue by updating the feeling-responsive config.yml and a few other phlow.de references.

If you have experience in jekyll and the feeling-responsive theme, I'd certainly welcome some help on some more issues.  Let me know.
